spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: false

springdoc:
  api-docs:
    enabled: ${ENABLE_SWAGGER:true}

logging:
  level:
    root: INFO

server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
  info:
    defaults:
      enabled: false
    git:
      enabled: true
      mode: "full"
    java:
      enabled: true
